services:
  fuiz:
    build:
      context: .
    container_name: fuiz
    restart: unless-stopped
    ports:
      - 3000:3000
      - 5040:5040
      - 8080:8080
    volumes:
      - ./quizzes:/fuiz/quizzes
      - ./data:/fuiz/data
     