
services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    environment:
      - NETWORK_ORIGIN=http://frontend:8787
    ports:
      - "5040:5040"
    volumes:
      - backend-data:/app/data

  corkboard:
    build:
      context: .
      dockerfile: docker/Dockerfile.corkboard
    environment:
      - NETWORK_ORIGIN=http://frontend:8787
    ports:
      - "8080:8080"
    volumes:
      - corkboard-data:/app/data

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    environment:
      - PUBLIC_BACKEND_URL=http://backend:5040
      - PUBLIC_WS_URL=ws://backend:5040
      - PUBLIC_CORKBOARD_URL=http://corkboard:8080
      - NODE_ENV=production
      - AUTH_SECRET=your_secret_key
    ports:
      - "8787:8787"
    depends_on:
      - backend
      - corkboard

volumes:
  backend-data:
  corkboard-data: