FROM node:22-bookworm-slim
WORKDIR /app
COPY ../frontend .
RUN npm install -g bun@latest wrangler@latest
RUN bun install --frozen-lockfile
RUN bun run build
EXPOSE 3000
CMD ["wrangler", "dev", "--compatibility-flags=nodejs_compat", "--port", "3000", "--local-protocol=http", "--host=0.0.0.0"]
