FROM rust:1.87-bullseye AS builder
WORKDIR /app
COPY ../backend .
RUN cargo build --release --all-features

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/target/release/fuiz-server .
EXPOSE 5040
CMD ["./fuiz-server"]
