FROM node:22-bookworm-slim
WORKDIR /app
COPY ../frontend .
RUN npm install -g bun@latest wrangler@latest
RUN bun install --frozen-lockfile
EXPOSE 3000
ARG AUTH_SECRET
ENV AUTH_SECRET=${AUTH_SECRET}
# Use wrangler to serve the frontend application
ENTRYPOINT [ "bun" ]
CMD ["run", "preview", "--", "--ip", "0.0.0.0", "--var", "AUTH_SECRET:${AUTH_SECRET}"]